name: Mrunalini
channels:
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0=py38_0
  - alabaster=0.7.12=py_0
  - anaconda=2020.07=py38_0
  - anaconda-client=1.7.2=py38_0
  - anaconda-navigator=1.9.12=py38_0
  - anaconda-project=0.8.4=py_0
  - argh=0.26.2=py38_0
  - asn1crypto=1.3.0=py38_0
  - astroid=2.4.2=py38_0
  - atomicwrites=1.4.0=py_0
  - attrs=19.3.0=py_0
  - autopep8=1.5.3=py_0
  - babel=2.8.0=py_0
  - backcall=0.2.0=py_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - backports.shutil_get_terminal_size=1.0.0=py38_2
  - backports.tempfile=1.0=py_1
  - backports.weakref=1.0.post1=py_1
  - beautifulsoup4=4.9.1=py38_0
  